In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing import image
from tensorflow.keras import models, layers
from tensorflow.keras.applications import ResNet50
from keras.applications.resnet50 import preprocess_input

# Define input layer
input_layer = layers.Input(shape=(48, 48, 3))

model_resnet = ResNet50(weights='imagenet', input_tensor=input_layer, include_top=False)
last_layer = model_resnet.output
flatten = layers.Flatten()(last_layer)

# Add dense layers
dense1 = layers.Dense(100, activation='relu')(flatten)
dense2 = layers.Dense(100, activation='relu')(dense1)

# Add dense layer to the final output layer
output_layer = layers.Dense(10, activation='softmax')(dense2)

# Create model with input and output layer
model_m = models.Model(inputs=input_layer, outputs=output_layer)

# Freeze layers except the dense layers
for layer in model_m.layers[:-1]:
    layer.trainable = False

# Compile the model
model_m.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Load MNIST dataset
(x_train_m, y_train_m), (x_test_m, y_test_m) = mnist.load_data()

# Load and preprocess the MNIST dataset
x_train_m = np.expand_dims(x_train_m, axis=-1)
x_test_m = np.expand_dims(x_test_m, axis=-1)
x_train_m = np.repeat(x_train_m, 3, axis=-1)
x_test_m = np.repeat(x_test_m, 3, axis=-1)
x_train_m = tf.image.resize(x_train_m, (48, 48))
x_test_m = tf.image.resize(x_test_m, (48, 48))
x_train_m = x_train_m / 255.0
x_test_m = x_test_m / 255.0

# Convert labels to categorical format
y_train_m = to_categorical(y_train_m, 10)
y_test_m = to_categorical(y_test_m, 10)

# Train the model
training_m = model_m.fit(x_train_m, y_train_m, epochs=15, batch_size=200, verbose=True, validation_data=(x_test_m, y_test_m))


Epoch 1/15
300/300 [==============================] - 28s 52ms/step - loss: 0.4669 - accuracy: 0.8562 - val_loss: 0.1887 - val_accuracy: 0.9424
Epoch 2/15
300/300 [==============================] - 15s 49ms/step - loss: 0.1909 - accuracy: 0.9395 - val_loss: 0.1640 - val_accuracy: 0.9473
Epoch 3/15
300/300 [==============================] - 15s 52ms/step - loss: 0.1420 - accuracy: 0.9545 - val_loss: 0.1547 - val_accuracy: 0.9493
Epoch 4/15
300/300 [==============================] - 15s 50ms/step - loss: 0.1283 - accuracy: 0.9580 - val_loss: 0.1448 - val_accuracy: 0.9535
Epoch 5/15
300/300 [==============================] - 16s 52ms/step - loss: 0.1181 - accuracy: 0.9610 - val_loss: 0.1152 - val_accuracy: 0.9633
Epoch 6/15
300/300 [==============================] - 15s 51ms/step - loss: 0.1070 - accuracy: 0.9651 - val_loss: 0.0954 - val_accuracy: 0.9694
Epoch 7/15
300/300 [==============================] - 15s 49ms/step - loss: 0.1032 - accuracy: 0.9655 - val_loss: 0.1091 - val_accuracy:

In [ ]:
# Evaluate the model on MNIST testing samples
y_pred_m = model_m.predict(x_test_m)
y_pred_classes_m = np.argmax(y_pred_m, axis=1)
y_true_m = np.argmax(y_test_m, axis=1)



# Compute confusion matrix, precision, recall, and F1 score
confusion_m = confusion_matrix(y_true_m, y_pred_classes_m)
precision_m = precision_score(y_true_m, y_pred_classes_m, average='weighted')
recall_m = recall_score(y_true_m, y_pred_classes_m, average='weighted')
f1_m = f1_score(y_true_m, y_pred_classes_m, average='weighted')

print("Confusion Matrix (MNIST):")
print(confusion_m)
print(f"Precision (MNIST): {precision_m}")
print(f"Recall (MNIST): {recall_m}")
print(f"F1 Score (MNIST): {f1_m}")

313/313 [==============================] - 5s 13ms/step
Confusion Matrix (MNIST):
[[ 975    0    0    0    0    1    1    0    2    1]
 [   1 1126    2    0    0    0    0    5    0    1]
 [   7    1  995    6    0    1    1    6   11    4]
 [   1    1    2  965    0   15    0    2   14   10]
 [   1    0    0    0  914    0    5   10   10   42]
 [   1    0    1    5    0  868    0    2   13    2]
 [  16    3    1    1    0   11  916    0   10    0]
 [   3    1    2    1    1    0    0 1010    1    9]
 [   0    0    0    2    1    4    0    3  955    9]
 [   5    0    0    4    1    3    0    2    8  986]]
Precision (MNIST): 0.9717985881513723
Recall (MNIST): 0.971
F1 Score (MNIST): 0.9710643695868517


In [ ]:
# Creating modle with input and output layer
model_f=models.Model(inputs=input_layer,outputs=output_layer)

for layer in model_f.layers[:-1]:
    layer.trainable=False

# Compiling Model

model_f.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [ ]:
# Load Fashion MNIST dataset
from tensorflow.keras.datasets import fashion_mnist
(x_train_f, y_train_f), (x_test_f, y_test_f) = fashion_mnist.load_data()

# Load and preprocess the MNIST dataset

x_train_f= np.expand_dims(x_train_f, axis=-1)  # Add channel dimension
x_test_f= np.expand_dims(x_test_f, axis=-1)
x_train_f = np.repeat(x_train_f, 3, axis=-1)  # Convert to 3 channels image
x_test_f = np.repeat(x_test_f, 3, axis=-1)
x_train_f = tf.image.resize(x_train_f, (48, 48))  # Resize images to (48, 48)
x_test_f = tf.image.resize(x_test_f, (48, 48))
x_train_f.shape, x_test_f.shape

(TensorShape([60000, 48, 48, 3]), TensorShape([10000, 48, 48, 3]))

In [ ]:
# Normalize pixel values to be between 0 and 1
x_train_f= x_train_f / 255.0
x_test_f = x_test_f / 255.0

# Convert labels to categorical format
y_train_f= to_categorical(y_train_f, 10)
y_test_f= to_categorical(y_test_f, 10)

In [ ]:

training_f = model_f.fit(x_train_f,y_train_f,epochs=15,batch_size=200,verbose=True,validation_data=(x_test_f,y_test_f))

Epoch 1/15
300/300 [==============================] - 15s 51ms/step - loss: 0.8270 - accuracy: 0.7100 - val_loss: 0.8405 - val_accuracy: 0.6991
Epoch 2/15
300/300 [==============================] - 15s 51ms/step - loss: 0.8226 - accuracy: 0.7107 - val_loss: 0.8348 - val_accuracy: 0.7038
Epoch 3/15
300/300 [==============================] - 15s 51ms/step - loss: 0.8185 - accuracy: 0.7113 - val_loss: 0.8299 - val_accuracy: 0.7031
Epoch 4/15
300/300 [==============================] - 15s 51ms/step - loss: 0.8147 - accuracy: 0.7140 - val_loss: 0.8251 - val_accuracy: 0.7095
Epoch 5/15
300/300 [==============================] - 15s 51ms/step - loss: 0.8109 - accuracy: 0.7143 - val_loss: 0.8273 - val_accuracy: 0.7110
Epoch 6/15
300/300 [==============================] - 15s 51ms/step - loss: 0.8088 - accuracy: 0.7149 - val_loss: 0.8209 - val_accuracy: 0.7080
Epoch 7/15
300/300 [==============================] - 15s 49ms/step - loss: 0.8056 - accuracy: 0.7167 - val_loss: 0.8206 - val_accuracy:

In [ ]:
# Evaluate the model on Fashion MNIST testing samples
y_pred_f = model_f.predict(x_test_f)
y_pred_classes_f= np.argmax(y_pred_f, axis=1)
y_true_f = np.argmax(y_test_f, axis=1)


# Compute confusion matrix, precision, recall, and F1 score
confusion_f= confusion_matrix(y_true_f, y_pred_classes_f)
precision_f = precision_score(y_true_f, y_pred_classes_f, average='weighted')
recall_f = recall_score(y_true_f, y_pred_classes_f, average='weighted')
f1_f = f1_score(y_true_f, y_pred_classes_f, average='weighted')

print("(Fashion MNIST):")
print("Confusion Matrix :")
print(confusion_f)
print(f"Precision : {precision_f}")
print(f"Recall : {recall_f}")
print(f"F1 Score : {f1_f}")

313/313 [==============================] - 4s 12ms/step
(Fashion MNIST):
Confusion Matrix :
[[737   9  31  68  20   5  68  17  43   2]
 [  2 890  18  48  12   0  22   0   8   0]
 [ 24   9 615  18 137   4 145   3  41   4]
 [ 92  44  10 704  35   2  79   1  30   3]
 [ 23  10 224  80 516   0 124   0  22   1]
 [  3   0   1   2   0 763   1 149  23  58]
 [207  17 276  80 112   1 246   2  59   0]
 [  1   0   0   0   0  69   0 841   3  86]
 [ 57   9  31   7  30  24  37  33 758  14]
 [  2   0   3   3   2  14   0  58   6 912]]
Precision : 0.6921095365309139
Recall : 0.6982
F1 Score : 0.6926119462331434


In MNIST_Fashion with 2 epoc --> F1 =0.5

In MNIST_Fashion with 10 epoc --> F1 =0.68

In MNIST_Fashion with 15 epoc --> F1 =0.7

In [ ]:
model_f.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 48, 48, 3)]          0         []                            
                                                                                                  
 conv1_pad (ZeroPadding2D)   (None, 54, 54, 3)            0         ['input_1[0][0]']             
                                                                                                  
 conv1_conv (Conv2D)         (None, 24, 24, 64)           9472      ['conv1_pad[0][0]']           
                                                                                                  
 conv1_bn (BatchNormalizati  (None, 24, 24, 64)           256       ['conv1_conv[0][0]']          
 on)                                                                                        